# Generated by Django 3.1.3 on 2020-12-31 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Type', models.CharField(choices=[('Doc', 'Doc'), ('Steel', 'Steel'), ('Box', 'Box')], default='Box', max_length=12)),
                ('ProductName', models.CharField(max_length=25)),
                ('CreatingDate', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('hasShip', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
