# Generated by Django 3.1.3 on 2020-12-31 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ship_Type', models.CharField(choices=[('Uçak', 'Plane'), ('Kamyon', 'Truck'), ('Gemi', 'Ship')], default='Kamyon', max_length=10)),
                ('Locations_Type', models.CharField(choices=[('Mersin', 'Mersin'), ('Istanbul', 'Istanbul')], default='Mersin', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=False)),
                ('TrackingId', models.CharField(default=uuid.uuid4, editable=False, max_length=40)),
                ('SippingContent', models.CharField(max_length=100)),
                ('ShippingNotes', models.TextField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('ArrivingDate', models.DateTimeField()),
                ('DepartureDate', models.DateTimeField(auto_now_add=True)),
                ('Ports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_set', to='Port.port')),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_set', to='Product.product')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
